### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by desertedeagle8383** [Un67/Quiz#1]
Sammy, can you add a toString method to Domain? I need it for MainMenuPanel.

**Comment by Un67** [comment]
Does this happen to be for the JList? I encountered a similar problem with Question. My solution was to create a subclass of DefaultQuestionCellRenderer, which I set the JLIst to use.

If that's the problem, try this code:

private class DomainCellRenderer extends DefaultListCellRenderer {
		public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
			super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
			Domain domain = (Question) value;
			setText(domain.getName());
			return this;
		}
	}

**Comment by desertedeagle8383** [comment]
Doesn't having a toString method make it easier anyway? Yours makes sense to have a subclass of DomainCellRenderer because of your tooltip but all mine needs is the name of the Domain object. I think it's simpler just to have a toString method.

**Comment by Un67** [comment]
I guess it works either way, I just figured that doing it this way would be less dependent on having other people change their code.

**Comment by desertedeagle8383** [comment]
Weijia try clicking the New Domain button on the MainMenuPanel I just updated. I'm using setLeDomain with a new blank Domain object that I set the title as New Domain. This doesn't save anything, so I don't think it should be a problem since it's just an isolated Domain object until you need to add it to the Profile and save it to the XML file when you click Done.

**Comment by Un67** [comment]
I tried it and it did nothing, although I commented out a lot of code because of compiler errors, so I'm not sure if that was an accurate diagnosis.

**Comment by desertedeagle8383** [comment]
Really? I have it successfully going to your DomainEditPanel (which has no errors as of the version uploaded to GitHub right now) from both New Domain and Edit Domain. I'll upload the latest versions of Quiz and MainMenuPanel right now.

**Comment by Un67** [comment]
OK, it works now. Must have been something I commented out.

**Comment by desertedeagle8383** [comment]
I'm updating MainMenuPanel again. Try using Edit Domain now. This is pretty cool.

**Comment by GiornoGiovana** [comment]
Does anyone know how to put in the textfields in the Jradio buttons?  I
tried using this.add() for the textfields within the Jradios, but the end
result becomes a cluster of weird code. Thanks.

On Fri, Mar 6, 2015 at 10:47 PM, desertedeagle8383 <notifications@github.com

**Comment by Un67** [comment]
I don't think you can put text fields within the JRadioButtons themselves. What I would do is leave some blank space between two of the words for adding a JTextField, which you can enable or disable depending on whatever option is selected. If that proves too difficult, maybe we could consider asking Mrs. Gerb to change the panel so that the text field is placed away from the option itself.

**Comment by GiornoGiovana** [comment]
All right. Also for the quizOptionsActionListener does the options selected
get saved somewhere? And does that all happen if if a person were to select
the ok button after selecting options?

**Comment by GiornoGiovana** [comment]
Also can a person select more than one question order/question select? I
know it may sound like a dumb question, but I want to do a double check.

**Comment by Un67** [comment]
There should actually not be a single quizOptionsActionListener. Instead, you should have an action listener for both the OK and Cancel buttons. The options will be saved in the future, but you don't need to worry about that for now. And no, a person cannot select more than one question order or question selection.

**Comment by GiornoGiovana** [comment]
Thanks for telling me.

**Comment by GiornoGiovana** [comment]
So for now I don't have to worry about the ActionListener for changing the
quiz options?

**Comment by GiornoGiovana** [comment]
So unit testing is tomorrow right? In that case do I have to make the quiz
options listener save data for the test? Or do I just leave it blank since
it is an early version?

**Comment by Un67** [comment]
Just get the interface working for now. You can worry about that stuff later.

**Comment by GiornoGiovana** [comment]
Ok. Thanks.
