### ISSUE TITLE
MouseListener in DomainEditPanel

### ISSUE THREAD

**Issue by desertedeagle8383** [Un67/Quiz#3]
Weijia, I noticed that you're using a MouseListener to activate your buttons, but that activates the buttons even if you click in white space under the list of questions. A cleaner implementation would be with a ListSelectionListener on your JList, which check executes its code whenever the selection in the list changes, and checking if anything is selected in the JList with isSelectionEmpty.

**Comment by Un67** [comment]
Well, clicking the white space under the list of questions does count as a selection, though, because it makes you select the bottom question. I felt that doing it this way makes things more consistent.

**Comment by desertedeagle8383** [comment]
The problem I see with it is that once it's activated, there's never a case that deactivates the buttons. A ListSelectionListener would take care of that.

**Comment by Un67** [comment]
I've thought over this a bit, and realized that within my current implementation of DomainEditPanel, the only time in which there will be no selection will be after a Question is deleted. (When a Question is moved through drag and drop, it remains selected.) What I've done, then, is added code to disable the Delete and Edit buttons to the ActionListener for the Delete button. I think that this keeps the implementation robust and makes a ListSelectionListener unnecessary.

**Comment by desertedeagle8383** [comment]
I'm not 100% sure because I haven't looked at your code completely, but I don't think it accounts for when you edit a different domain, in which case the buttons would still be activated from the previous domain. I still think a ListSelectionListener is the best implementation since it means you only need one listener attached to the list to handle all cases with no exceptions, whereas adding these lines of code to different buttons allows for cases we may not think of. It takes care of everything under all circumstances in a direct manner, rather than doing it in a roundabout way.

**Comment by Un67** [comment]
OK, point taken. I followed your suggestion and made it use a ListSelectionListener instead. I've tested it out with switching back and forth between our two panels and it seems to work now.
