### ISSUE TITLE
Commited changes complication

### ISSUE THREAD

**Issue by Omnomnomivore** [Un67/Quiz#4]
just a few minutes ago, I committed my classes and synced with the project, and I reverted a change that Mark had made earlier today when he accidentally replaced the code in the profile class with the code in the domain class. He fixed this issue, but my synchronizing screwed it up again, so I reccommend that everyone gives the classes they changed today a once over to make sure that none of the changes disappeared.

**Comment by Un67** [comment]
It seemed fine for me for the most part, but I made some changes to the Quiz and MainMenuPanel classes because some of what I did in class seemed to be overridden.
